# -*- coding: utf-8 -*-
"""Deploy1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O__G5Z3v2rWx2tF1j2ph5JDsElbe7L-x
"""


import numpy as np
import pickle
import pandas as pd
import streamlit as st

from PIL import Image

filename = 'finalized_model.sav'

pickle_in = open(filename,"rb")
classifier=pickle.load(pickle_in)

def welcome():
    return "Welcome ALL"
def predict_bankruptcy(industrial_risk,management_risk,financial_flexibility,credibility,competitiveness,operating_risk):

    
prediction=classifier.predict([[industrial_risk,management_risk,financial_flexibility,credibility,competitiveness,operating_risk]])
     print(prediction)
     return prediction

def main():
    st.title("Bankruptcy Detector")
    html_temp = """
    <div style="background-color:tomato;padding:10px">
    <h2 style="color:white;text-align:center;">Streamlit Bankruptcy Detector ML App </h2>
    </div>
    """
    st.markdown(html_temp,unsafe_allow_html=True)
    industrial_risk = st.text_input("Industrial Risk",placeholder = "Type Here")
    management_risk = st.text_input("Management Risk",placeholder ="Type Here")
    financial_flexibility = st.text_input("financial_flexibility",placeholder ="Type Here")
    credibility = st.text_input("credibility",placeholder ="Type Here")
    competitiveness = st.text_input("competitiveness",placeholder ="Type Here")
    operating_risk = st.text_input("operating_risk",placeholder ="Type Here")
    #result_new=welcome()
    result_new = "..."
    if st.button("Predict"):
        result=predict_bankruptcy(industrial_risk,management_risk,financial_flexibility,credibility,competitiveness,operating_risk)
        if result == 0:
          result_new = "Bankruptcy"
        else:
          result_new = "Non-bankruptcy"
    st.success('The output is {}'.format(result_new))
   

if __name__=='__main__':
    main()